/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_MainWindow (void);
GtkWidget* create_AddBreakPointWindow (void);
GtkWidget* create_DebuggerSettingsWindow (void);
GtkWidget* create_aboutdialog (void);
