/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#	include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "globals.h"

GtkWidget *MainWindow;

int main (int argc, char *argv[])
{
	GtkWidget *AddBreakPointWindow;
	GtkWidget *DebuggerSettingsWindow;
	GtkWidget *stack_view;
	GtkCellRenderer *r1, *r2;
	GtkTreeViewColumn *column1;
	GtkListStore *store;
	GtkTreeSelection *selection;

	gtk_set_locale();
	gtk_init(&argc, &argv);

	add_pixmap_directory(PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

	MainWindow = create_MainWindow();

	g_signal_connect(MainWindow, "delete_event", gtk_main_quit, NULL);

	/* Setup the store */
	store = gtk_list_store_new(STACK_N_COLUMNS, G_TYPE_STRING, G_TYPE_STRING, G_TYPE_STRING);

	/* Add the columns for the stackview */
 	stack_view = lookup_widget(GTK_WIDGET(MainWindow), "stack_view");

 	r1 = gtk_cell_renderer_text_new();
	g_object_set(r1, "font-desc", pango_font_description_from_string ("sans 8"), "xalign", 0.99999, NULL);
 	r2 = gtk_cell_renderer_text_new();
	g_object_set(r2, "font-desc", pango_font_description_from_string ("sans 8"), NULL);

	gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(stack_view), -1, "#", r1, "text", STACK_NR_COLUMN, NULL);
	gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(stack_view), -1, "Function", r2, "text", STACK_FUNCTION_COLUMN, NULL);
	gtk_tree_view_insert_column_with_attributes(GTK_TREE_VIEW(stack_view), -1, "Location", r2, "text", STACK_LOCATION_COLUMN, NULL);

	gtk_tree_view_set_model(GTK_TREE_VIEW(stack_view), GTK_TREE_MODEL(store));

	selection = gtk_tree_view_get_selection(GTK_TREE_VIEW(stack_view));
	gtk_tree_selection_set_select_function(selection, stack_selection_function, NULL, NULL);

	gtk_window_maximize(MainWindow);
	gtk_widget_show(MainWindow);

	start_server(9000);

	gtk_main();
	return 0;
}

